# Generated by Django 4.2.7 on 2024-02-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
