# Generated by Django 4.2.7 on 2024-02-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_timeclock_clock_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclock',
            name='time_worked',
            field=models.IntegerField(default=0),
        ),
    ]
