# Generated by Django 4.2.7 on 2024-02-02 18:46

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclock',
            name='location',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
    ]
