# Generated by Django 4.2.7 on 2024-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_timeclock_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='location',
            field=models.CharField(blank=True, default='none'),
        ),
    ]
